# View cart
Eo_EcommerceBundle_Cart_View:
    defaults: { _controller:  EoEcommerceBundle:Cart:index }
    pattern:  /cart

# Checkout
Eo_EcommerceBundle_Cart_Add:
    defaults: { _controller:  EoEcommerceBundle:Cart:add }
    pattern:  /cart/add
    methods: [POST]

# Checkout
Eo_EcommerceBundle_Cart_Checkout:
    defaults: { _controller:  EoEcommerceBundle:Cart:checkout }
    pattern:  /checkout
